# This is the correspondence table between "committer email" of Git commits and
# SVN_ACCOUNT_NAME (set in ~git/.ssh/authorized_keys for each SSH key).
# See `bin/check-email-and-refname.rb` for details.
#
# You can add a new email address but DO NOT DELETE already-registered email address.
# This association will be used for committer identification of the ruby repository.
#
a_matsuda:
  - ronnie@dio.jp
# aamine
# akira
# akiyoshi
akr:
  - akr@fsij.org
# alanwu
# arai
# arton
aycabta:
  - aycabta@gmail.com
ayumin:
  - ayumu.aizawa@gmail.com
# azav
# chad
# charliesome
# dave
# davidflanagan
# dblack
# drbrain
duerst:
  - duerst@it.aoyama.ac.jp
eban:
  - eban@os.rim.or.jp
# emboss
eregon:
  - eregontp@gmail.com
  - eregon@ruby-lang.org
# evan
# funny_falcon
git:
  - svn-admin@ruby-lang.org
glass:
  - glass.saga@gmail.com
# gogotanaka
# gotoken
# gotoyuzo
# gsinclair
# H_Konishi
# headius
# hone
hsbt:
  - hsbt@ruby-lang.org
# iwamatsu
# jeg2
jeremy:
  - code@jeremyevans.net
# jim
k0kubun:
  - takashikkbn@gmail.com
# kanemoto
# katsu
kazu:
  - zn@mbf.nifty.com
# keiju
knu:
  - knu@idaemons.org
ko1:
  - ko1@atdot.net
kosaki:
  - kosaki.motohiro@gmail.com
# kosako
kou:
  - kou@cozmixng.org
  - kou@clear-code.com
# kouji
# ksaito
ktsj:
  - kazuki@callcc.net
# luislavena
mame:
  - mame@ruby-lang.org
marcandre:
  - github@marc-andre.ca
  - marcandre@ruby-lang.org
matz:
  - matz@ruby.or.jp
# michal
# mneumann
# moonwolf
mrkn:
  - mrkn@ruby-lang.org
  - mrkn@mrkn.jp
  - muraken@gmail.com
nagachika:
  - nagachika@ruby-lang.org
# nagai
# nahi
# nari
naruse:
  - naruse@airemix.jp
ngoto:
  - ngotogenome@gmail.com
nobu:
  - nobu@ruby-lang.org
normal:
  - normal@ruby-lang.org
# ntalbott
# ocean
odaira:
  - rodaira@us.ibm.com
# okkez
# rhe
# ryan
samuel:
  - samuel.williams@oriontransfer.co.nz
seki:
  - m_seki@mva.biglobe.ne.jp
# ser
# shigek
# shirosaki
shugo:
  - shugo@ruby-lang.org
shyouhei:
  - shyouhei@ruby-lang.org
# siena
# sonots
sorah:
  - her@sorah.jp
  - sorah@cookpad.com
soutaro:
  - matsumoto@soutaro.com
stomar:
  - sto.mar@web.de
suke:
  - masaki.suketa@nifty.ne.jp
tadd:
  - tad.a.digger@gmail.com
  - tadd@ruby-lang.org
# tadf
# takano32
# tarui
# technorama
tenderlove:
  - aaron.patterson@gmail.com
  - tenderlove@ruby-lang.org
# tmm1
# toyoshim
# ts
# ttate
# uema2
usa:
  - usa@ruby-lang.org
# wanabe
# watson1978
# wakou
# why
# wew
# wyhaines
# xibbar
yugui:
  - yugui@yugui.jp
yui-knk:
  - yui-knk@ruby-lang.org
yuki:
  - yk.nishijima@gmail.com
# zsombor
# zzak
