# This is the correspondence table between "committer email" of Git commits and
# SVN_ACCOUNT_NAME (set in ~git/.ssh/authorized_keys for each SSH key).
# See `bin/check-email-and-refname.rb` for details.
#
# You can add a new email address but DO NOT DELETE already-registered email address.
# This association will be used for committer identification of the ruby repository.
#
a_matsuda:
  - ronnie@dio.jp
# aamine
# akira
# akiyoshi
akr:
  - akr@fsij.org
alanwu:
  - alanwu@ruby-lang.org
# arai
# arton
aycabta:
  - aycabta@gmail.com
ayumin:
  - ayumu.aizawa@gmail.com
# azav
burdettelamar:
  - burdettelamar@yahoo.com
  - burdettelamar@ruby-lang.org
byroot:
  - jean.boussier@gmail.com
  - byroot@ruby-lang.org
# chad
# charliesome
# dave
# davidflanagan
# dblack
# drbrain
duerst:
  - duerst@it.aoyama.ac.jp
# eban
# emboss
eightbitraptor:
  - eightbitraptor@ruby-lang.org
  - matt@eightbitraptor.com
eileencodes:
  - eileencodes@gmail.com
eregon:
  - eregontp@gmail.com
  - eregon@ruby-lang.org
# evan
# funny_falcon
git:
  - svn-admin@ruby-lang.org
glass:
  - glass.saga@gmail.com
# gogotanaka
# gotoken
# gotoyuzo
# gsinclair
# H_Konishi
headius:
  - headius@headius.com
# hone
hsbt:
  - hsbt@ruby-lang.org
ima1zumi:
  - mariimaizumi5@gmail.com
# iwamatsu
jaruga:
  - jaruga@ruby-lang.org
# jeg2
jemma:
  - jemmaissroff@gmail.com
jeremy:
  - code@jeremyevans.net
jhawthorn:
  - john@hawthorn.email
  - jhawthorn@ruby-lang.org
# jim
kddnewton:
  - kddnewton@gmail.com
k0kubun:
  - takashikkbn@gmail.com
# kanemoto
katei:
  - kateinoigakukun@gmail.com
# katsu
kazu:
  - zn@mbf.nifty.com
# keiju
kjtsanaktsidis:
  - ktsanaktsidis@zendesk.com
  - kj@kjtsanaktsidis.id.au
knu:
  - knu@idaemons.org
ko1:
  - ko1@atdot.net
kosaki:
  - kosaki.motohiro@gmail.com
# kosako
kou:
  - kou@cozmixng.org
  - kou@clear-code.com
# kouji
# ksaito
ktsj:
  - kazuki@callcc.net
# luislavena
makenowjust:
  - make.just.on@gmail.com
mame:
  - mame@ruby-lang.org
marcandre:
  - github@marc-andre.ca
  - marcandre@ruby-lang.org
matz:
  - matz@ruby.or.jp
max:
  - ruby@bernsteinbear.com
maximecb:
  - maximecb@ruby-lang.org
  - maxime.chevalierboisvert@shopify.com
# michal
# mneumann
# moonwolf
mrkn:
  - mrkn@ruby-lang.org
  - mrkn@mrkn.jp
  - muraken@gmail.com
nagachika:
  - nagachika@ruby-lang.org
# nagai
# nahi
# nari
naruse:
  - naruse@airemix.jp
ngoto:
  - ngotogenome@gmail.com
nobu:
  - nobu@ruby-lang.org
normal:
  - normal@ruby-lang.org
# ntalbott
# ocean
odaira:
  - rodaira@us.ibm.com
okkez:
  - okkez000@gmail.com
ono-max:
  - onoto1998@gmail.com
peter.zhu:
  - peter@peterzhu.ca
  - peter.zhu@ruby-lang.org
pocke:
  - kuwabara@pocke.me
rhe:
  - k@rhe.jp
# ryan
samuel:
  - samuel.williams@oriontransfer.co.nz
schneems:
  - richard.schneeman@gmail.com
# seki
# ser
# shigek
shioimm:
  - shioi.mm@gmail.com
shirosaki:
  - h.shirosaki@gmail.com
shugo:
  - shugo@ruby-lang.org
shyouhei:
  - shyouhei@ruby-lang.org
# siena
# sonots
sorah:
  - her@sorah.jp
  - sorah@cookpad.com
soutaro:
  - matsumoto@soutaro.com
stomar:
  - sto.mar@web.de
# suke
tadd:
  - tad.a.digger@gmail.com
  - tadd@ruby-lang.org
# tadf
tagomoris:
  - tagomoris@gmail.com
takano32:
  - takano32@gmail.com
  - takano32@ruby-lang.org
# tarui
# technorama
tenderlove:
  - aaron.patterson@gmail.com
  - tenderlove@ruby-lang.org
# tmm1
tompng:
  - tomoyapenguin@gmail.com
# toyoshim
# ts
# ttate
# uema2
usa:
  - usa@ruby-lang.org
# wanabe
watson1978:
  - watson1978@gmail.com
# wakou
# why
# wew
# wyhaines
# xibbar
ydah:
  - t.yudai92@gmail.com
yugui:
  - yugui@yugui.jp
yui-knk:
  - yui-knk@ruby-lang.org
yuki:
  - yk.nishijima@gmail.com
zenspider:
  - ryand-github@zenspider.com
  - ryand-ruby@zenspider.com
  - zenspider@gmail.com
# zsombor
zverok:
  - zverok.offline@gmail.com
  - zverok@ruby-lang.org
zzak:
  - zzak@hey.com
  - zzakscott@gmail.com
